insert into Show (Title, CoverImage, Cancelled, Approved) values ('Holidays by the Sea (Ni à vendre ni à louer)', 'http://dummyimage.com/117x100.png/ff4444/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Phantom of Liberty, The (Fantôme de la liberté, Le)', 'http://dummyimage.com/152x100.png/cc0000/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Calvary', 'http://dummyimage.com/220x100.png/ff4444/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Dukes, The', 'http://dummyimage.com/244x100.png/5fa2dd/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Alvin and the Chipmunks: The Squeakquel', 'http://dummyimage.com/195x100.png/ff4444/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Something of Value', 'http://dummyimage.com/142x100.png/dddddd/000000', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Fist of the North Star', 'http://dummyimage.com/207x100.png/ff4444/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('In Search of the Castaways', 'http://dummyimage.com/243x100.png/cc0000/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Summer of ''04 (Sommer ''04)', 'http://dummyimage.com/244x100.png/5fa2dd/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Devil Came on Horseback, The', 'http://dummyimage.com/126x100.png/cc0000/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Lolita', 'http://dummyimage.com/236x100.png/dddddd/000000', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Boxcar Bertha', 'http://dummyimage.com/102x100.png/5fa2dd/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Merry Madagascar', 'http://dummyimage.com/242x100.png/5fa2dd/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Bamako', 'http://dummyimage.com/114x100.png/cc0000/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Can Go Through Skin (Kan door huid heen)', 'http://dummyimage.com/212x100.png/dddddd/000000', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Shot in the Heart', 'http://dummyimage.com/138x100.png/5fa2dd/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('My Forbidden Past', 'http://dummyimage.com/153x100.png/ff4444/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Kinjite: Forbidden Subjects', 'http://dummyimage.com/155x100.png/ff4444/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Adventures of Mary-Kate and Ashley, The: The Case of the United States Navy Adventure', 'http://dummyimage.com/104x100.png/ff4444/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Seven Days in May', 'http://dummyimage.com/213x100.png/dddddd/000000', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Student of the Year', 'http://dummyimage.com/231x100.png/dddddd/000000', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Submerged', 'http://dummyimage.com/125x100.png/5fa2dd/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Laws of Gravity', 'http://dummyimage.com/181x100.png/cc0000/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Hero at Large', 'http://dummyimage.com/214x100.png/ff4444/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Mourning Becomes Electra', 'http://dummyimage.com/162x100.png/dddddd/000000', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Vlad', 'http://dummyimage.com/127x100.png/dddddd/000000', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Any Questions for Ben?', 'http://dummyimage.com/216x100.png/5fa2dd/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Captains of the Clouds', 'http://dummyimage.com/152x100.png/cc0000/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Charlie Chan in Paris', 'http://dummyimage.com/148x100.png/ff4444/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Collector, The (Komornik)', 'http://dummyimage.com/116x100.png/ff4444/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('El Escarabajo de Oro', 'http://dummyimage.com/175x100.png/cc0000/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Scarlet Diva', 'http://dummyimage.com/244x100.png/5fa2dd/ffffff', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('I Don''t Want to Talk About It (De eso no se habla)', 'http://dummyimage.com/168x100.png/cc0000/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Hunt, The (Jagten)', 'http://dummyimage.com/135x100.png/5fa2dd/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Alpha and Omega 2: A Howl-iday Adventure (Alpha & Omega 2)', 'http://dummyimage.com/234x100.png/ff4444/ffffff', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Daisy Miller', 'http://dummyimage.com/210x100.png/5fa2dd/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Nostalghia', 'http://dummyimage.com/190x100.png/ff4444/ffffff', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Stratton Story, The', 'http://dummyimage.com/239x100.png/5fa2dd/ffffff', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Stolen (Stolen Lives)', 'http://dummyimage.com/180x100.png/ff4444/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Best of Me', 'http://dummyimage.com/207x100.png/dddddd/000000', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Burglars, The (Le casse)', 'http://dummyimage.com/183x100.png/dddddd/000000', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Therese Raquin (a.k.a. Adultress, The)', 'http://dummyimage.com/137x100.png/dddddd/000000', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Detective (Détective)', 'http://dummyimage.com/157x100.png/ff4444/ffffff', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Next Step, The', 'http://dummyimage.com/208x100.png/5fa2dd/ffffff', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Flaming Creatures', 'http://dummyimage.com/234x100.png/cc0000/ffffff', 1, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Bang Boom Bang - Ein todsicheres Ding', 'http://dummyimage.com/214x100.png/5fa2dd/ffffff', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Stand Up Guys', 'http://dummyimage.com/232x100.png/cc0000/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Artifact', 'http://dummyimage.com/247x100.png/ff4444/ffffff', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Christmas with the Kranks', 'http://dummyimage.com/203x100.png/dddddd/000000', 0, 0);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Unspeakable Act, The', 'http://dummyimage.com/219x100.png/5fa2dd/ffffff', 1, 0);

insert into UserProfile (FirebaseUserId, UserName, Name, Email, Admin) values ('cGTcEAqYt0TB58tdDVOW5ZFuxT23', 'johnx', 'John Smith', 'x@x.com', 1);
insert into UserProfile (FirebaseUserId, UserName, Name, Email, Admin) values ('EbGua89LS5Yk5QaWYgbXKADYWz52', 'jbyrd4', 'Jury Byrd', 'jbyrd4@gmail.com', 0);
insert into UserProfile (FirebaseUserId, UserName, Name, Email, Admin) values ('McZM4oO91NNnHcUbr7g826V4dF43', 'obediahx', 'Obediah Smith', 'obediahx@gmail.com', 1);
insert into UserProfile (FirebaseUserId, UserName, Name, Email, Admin) values ('SGMT9jBh43Up', 'kambrosoli3', 'Kermy Ambrosoli', 'kambrosoli3@alexa.com', 1);
insert into UserProfile (FirebaseUserId, UserName, Name, Email, Admin) values ('B3ofYcbS8S', 'glarder4', 'Galvin Larder', 'glarder4@fda.gov', 1);

insert into Category (Name) values ('Currently Watching');
insert into Category (Name) values ('Finished');
insert into Category (Name) values ('Caught Up');
insert into Category (Name) values ('Lost Interest');
insert into Category (Name) values ('Potential');

insert into Platform (Name) values ('Netflix');
insert into Platform (Name) values ('Amazon Prime');
insert into Platform (Name) values ('Hulu');
insert into Platform (Name) values ('Peacock');
insert into Platform (Name) values ('HBO Max');
insert into Platform (Name) values ('YouTubeTV');
insert into Platform (Name) values ('AppleTV');
insert into Platform (Name) values ('Disney Plus');
insert into Platform (Name) values ('Cruncyroll');
insert into Platform (Name) values ('SlingTV');
insert into Platform (Name) values ('AcornTV');
insert into Platform (Name) values ('CBS All Access');
insert into Platform (Name) values ('Tubi');
insert into Platform (Name) values ('Fubo');

insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (4, 5, 2, 21, 4, 13, '12/27/2021', 'mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum', 12, 4);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (42, 1, 9, 11, 8, 5, '7/20/2021', 'erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus', 10, 2);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (22, 2, 1, 20, 4, 17, '4/30/2021', 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque', 3, 4);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (37, 4, 7, 4, 4, 17, '1/25/2022', 'accumsan tortor quis', 1, 5);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (23, 4, 8, 17, 5, 15, '2/25/2022', 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris', 2, 4);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (16, 3, 8, 15, 10, 7, '5/21/2021', 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam', 11, 4);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (35, 5, 8, 18, 2, 11, '10/28/2021', 'odio odio elementum eu interdum eu', 7, 5);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (20, 4, 3, 7, 2, 9, '5/24/2021', 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', 3, 1);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (6, 3, 3, 5, 2, 19, '5/13/2021', 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet', 11, 5);
insert into UserShow (ShowId, UserId, LastWatchedSeason, LastWatchedEpisode, LastReleasedSeason, LastReleasedEpisode, DateUpdated, Note, PlatformId, CategoryId) values (47, 2, 4, 12, 9, 9, '10/28/2021', 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 8, 5);