insert into Show (Title, CoverImage, Cancelled, Approved) values ('Big Bang Theory', 'https://flxt.tmsimg.com/assets/p185554_b_v10_az.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Blindspot', 'https://m.media-amazon.com/images/M/MV5BMDIyYzUwNjgtNDA1Mi00ZmQ3LThhNWQtN2RjZjczNjRlZmQ3XkEyXkFqcGdeQXVyNjMxNzcwOTI@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Brooklyn Nine Nine', 'https://m.media-amazon.com/images/M/MV5BNzVkYWY4NzYtMWFlZi00YzkwLThhZDItZjcxYTU4ZTMzMDZmXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Designated Survivor', 'https://m.media-amazon.com/images/M/MV5BZTdkMGNhZmYtNzAxMy00NWJkLThkN2MtNjVkNzY0NzVlMWQ4XkEyXkFqcGdeQXVyMTA0MDgzNTE1._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Girl Meets World', 'https://flxt.tmsimg.com/assets/p10757092_b_h9_ae.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Lethal Weapon', 'https://m.media-amazon.com/images/M/MV5BMzMyNzM1MTczM15BMl5BanBnXkFtZTgwNDg4MzA0NjM@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Nashville', 'https://m.media-amazon.com/images/M/MV5BMTEzNDE2Mjg0MTdeQTJeQWpwZ15BbWU4MDUxNTczNzAy._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('New Girl', 'https://m.media-amazon.com/images/M/MV5BMjA0MDc1NTk0Ml5BMl5BanBnXkFtZTgwMTk2ODA5NDM@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Orange is the New Black', 'https://upload.wikimedia.org/wikipedia/en/1/1f/Orange_is_the_new_black_season_6.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Prison Break', 'https://flxt.tmsimg.com/assets/p185128_b_v8_ah.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Quantico', 'https://m.media-amazon.com/images/M/MV5BMTkxNTg3MTc0Ml5BMl5BanBnXkFtZTgwMzYxNDIyNTM@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Sherlock', 'https://m.media-amazon.com/images/I/714nEMf6oyS._SL1500_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Sneaky Pete', 'https://m.media-amazon.com/images/M/MV5BMTc2OTExNDE3MF5BMl5BanBnXkFtZTgwMzk2MjU5NzM@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Leftovers', 'https://m.media-amazon.com/images/M/MV5BNTE3MDc1MjY4NV5BMl5BanBnXkFtZTgwMDg4MjQ4MTE@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Doctor Who', 'https://m.media-amazon.com/images/I/71XPVYAU+cL._SL1500_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Fear the Walking Dead', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/Fear_the_Walking_Dead_season_4.jpg/220px-Fear_the_Walking_Dead_season_4.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Game of Thrones', 'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Walking Dead', 'https://m.media-amazon.com/images/M/MV5BZmU5NTcwNjktODIwMi00ZmZkLTk4ZWUtYzVjZWQ5ZTZjN2RlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UY1200_CR83,0,630,1200_AL_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('WestWorld', 'https://m.media-amazon.com/images/M/MV5BMTRmYzNmOTctZjMwOS00ODZlLWJiZGQtNDg5NDY5NjE3MTczXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Supernatural', 'https://flxt.tmsimg.com/assets/p185113_b_v13_bh.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Timeless', 'https://m.media-amazon.com/images/M/MV5BMjA5ODkxODgzMl5BMl5BanBnXkFtZTgwNzA4MTc5NDM@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Blacklist', 'https://m.media-amazon.com/images/M/MV5BNDFkZDI5ZGUtYTdkOC00YTFiLWJjNjMtNTQ3ZjIxMTY2ZjMyXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_FMjpg_UX1000_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Last Man Standing', 'https://upload.wikimedia.org/wikipedia/en/1/1a/Last_Man_Standing_S9_Poster.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Sense 8', 'https://m.media-amazon.com/images/M/MV5BMTU3OTQwOTY2Ml5BMl5BanBnXkFtZTgwMjIzMjYxMjI@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Glee', 'https://m.media-amazon.com/images/M/MV5BYWJhZjNjZjUtM2JlZC00ZWE3LWJmZDItMDRhMWJkMTJhZDhkXkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_FMjpg_UX1000_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Hell on Wheels', 'https://upload.wikimedia.org/wikipedia/en/4/4e/Hell_on_Wheels_Season_3_DVD.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Grimm', 'https://m.media-amazon.com/images/M/MV5BMTkyODg2MzQwMV5BMl5BanBnXkFtZTgwNTA2MjE1MDI@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('True Detective', 'https://m.media-amazon.com/images/M/MV5BMmRlYmE0Y2UtNDk2Yi00NzczLWEwZTEtZmE2OTcyYzcxYmU5XkEyXkFqcGdeQXVyNTMxMjgxMzA@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Once Upon a Time', 'https://m.media-amazon.com/images/M/MV5BNjBmZmI0ZDktODI2MS00MDU1LTk0NDYtNGE0MDc0OWVkYzcwXkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Arrow', 'https://m.media-amazon.com/images/M/MV5BMTI0NTMwMDgtYTMzZC00YmJhLTg4NzMtMTc1NjI4MWY4NmQ4XkEyXkFqcGdeQXVyNTY3MTYzOTA@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Homeland', 'https://m.media-amazon.com/images/M/MV5BM2Q1YzUxYTYtOTkwZC00Mjk3LTllZWQtNThjYjllZjE2OTQwXkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Marvel: Agents of Shield', 'https://upload.wikimedia.org/wikipedia/en/a/a1/Agents_of_S.H.I.E.L.D._season_6_poster.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Gotham', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Gotham_%28season_5%29.jpg/220px-Gotham_%28season_5%29.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Flash', 'https://m.media-amazon.com/images/M/MV5BMDIzNzYwNTctZWY4Mi00YjQ2LWI5YWYtMzdmNDgwMGI4Yzk1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('24', 'https://m.media-amazon.com/images/M/MV5BMTg5OTkyNzA0NF5BMl5BanBnXkFtZTcwMDYyMDUwMg@@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('House of Cards', 'https://upload.wikimedia.org/wikipedia/en/0/0b/House_of_Cards_season_1.png', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Daredevil', 'https://flxt.tmsimg.com/assets/p11408531_b1t_v9_ab.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Community', 'https://m.media-amazon.com/images/I/81Sh1743JeL._SL1500_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Mad Men', 'https://static.wikia.nocookie.net/whumpapedia/images/5/54/Mad_Men.jpeg/revision/latest?cb=20211105131509', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('V', 'https://m.media-amazon.com/images/M/MV5BMTYxNTQ5NTg2Ml5BMl5BanBnXkFtZTcwODUyNTY5Mg@@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('X-Files', 'https://m.media-amazon.com/images/M/MV5BZDA0MmM4YzUtMzYwZC00OGI2LWE0ODctNzNhNTkwN2FmNTVhXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('FireFly', 'https://m.media-amazon.com/images/M/MV5BOTcwNzkwMDItZmM1OC00MmQ2LTgxYjgtOTNiNDgxZDAxMjk0XkEyXkFqcGdeQXVyNDQ0MTYzMDA@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Boy Meets World', 'https://m.media-amazon.com/images/M/MV5BMTkyMjAyNzAxNl5BMl5BanBnXkFtZTcwNjk1MDk5NA@@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Friends', 'https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Seinfeld', 'https://m.media-amazon.com/images/M/MV5BZjZjMzQ2ZmUtZWEyZC00NWJiLWFjM2UtMzhmYzZmZDcxMzllXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Roswell', 'https://m.media-amazon.com/images/M/MV5BZTc3MjgxMGQtMDQ3Ny00MDYyLWExY2EtMzFmYjAxZTdiMDk5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Lost', 'https://m.media-amazon.com/images/M/MV5BNzhlY2E5NDUtYjJjYy00ODg3LWFkZWQtYTVmMzU4ZWZmOWJkXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Heroes', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Heroes_Season_4.png/220px-Heroes_Season_4.png', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Prisoner', 'https://upload.wikimedia.org/wikipedia/en/f/f3/Amc-prisoner-comic-con-six.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Human Target', 'https://m.media-amazon.com/images/M/MV5BYTI3OWNiMzEtZDAzOS00MDU4LWEzNzItMTQzZmE2NGJjMDA3XkEyXkFqcGdeQXVyMTEyNzgwMDUw._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Sopranos', 'https://m.media-amazon.com/images/M/MV5BZGJjYzhjYTYtMDBjYy00OWU1LTg5OTYtNmYwOTZmZjE3ZDdhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Weeds', 'https://upload.wikimedia.org/wikipedia/en/2/28/Weeds-season-6-poster.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Fringe', 'https://flxt.tmsimg.com/assets/p186601_b_v9_ak.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('30 Rock', 'https://m.media-amazon.com/images/M/MV5BMTQ4NDQ4OTUzOV5BMl5BanBnXkFtZTcwMjMzMTUyNw@@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Chuck', 'https://m.media-amazon.com/images/M/MV5BMTM0ODIwNjI3NF5BMl5BanBnXkFtZTcwODU2ODUzMw@@._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Office', 'https://upload.wikimedia.org/wikipedia/en/5/58/TheOffice_S7_DVD.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Arrested Development', 'https://m.media-amazon.com/images/M/MV5BNTFlYTE2YTItZmQ1NS00ZWQ5LWI3OGUtYTQzNDMyZmEyYTZjXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Dexter', 'https://m.media-amazon.com/images/M/MV5BZjkzMmU5MjMtODllZS00OTA5LTk2ZTEtNjdhYjZhMDA5ZTRhXkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Breaking Bad', 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/202001/Breaking_Bad.jpeg?Ifrqi.v01Y0KfAlAyY172HCu8HZTJJvy&size=1200:675', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Smallville', 'https://m.media-amazon.com/images/M/MV5BYmNiNzlhOWItMDM5Mi00MGYzLWI1ZDYtNmI5NzI0MWFkMTIwXkEyXkFqcGdeQXVyNjU2NjA5NjM@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Sons of Anarchy', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3129/3129027_sa.jpg;maxHeight=640;maxWidth=550', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('How I Met Your Mother', 'https://m.media-amazon.com/images/M/MV5BNjg1MDQ5MjQ2N15BMl5BanBnXkFtZTYwNjI5NjA3._V1_FMjpg_UX1000_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Revolution', 'https://www.tvguide.com/a/img/catalog/provider/1/1/1-715410814.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('True Blood', 'https://m.media-amazon.com/images/I/51VwVoyYbRL._SY445_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Wilfred', 'https://m.media-amazon.com/images/M/MV5BMTUxMTk4NDIyMV5BMl5BanBnXkFtZTgwMDQ0MTAyMjE@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Sons of Guns', 'https://m.media-amazon.com/images/I/910PLkcfnmL._SL1500_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Two and a Half Men', 'https://upload.wikimedia.org/wikipedia/en/c/c9/Twoandahalfmen1.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Parks and Recreation', 'https://www.oregonlive.com/resizer/paQpZ0sNik61AUqeSxlPP_HliS8=/1280x0/smart/cloudfront-us-east-1.images.arcpublishing.com/advancelocal/QFY6S6OCHRHWZOXFIH4RN7IKBU.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('White Collar', 'https://m.media-amazon.com/images/M/MV5BNDI5MDgyMTYzNF5BMl5BanBnXkFtZTcwMjAwNzk1Mw@@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Hannibal', 'https://static.wikia.nocookie.net/hannibal/images/f/f6/HBL_Complete_Series_Poster.jpg/revision/latest?cb=20200625050724', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Limitless', 'https://m.media-amazon.com/images/M/MV5BMTA4ODE4NjA5ODleQTJeQWpwZ15BbWU4MDUxMTQ0NTYx._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Boys', 'https://m.media-amazon.com/images/M/MV5BNGEyOGJiNWEtMTgwMi00ODU4LTlkMjItZWI4NjFmMzgxZGY2XkEyXkFqcGdeQXVyNjcyNjcyMzQ@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Mayans MC', 'https://assets.fxnetworks.com/cms/prod/2021/05/06/web_largecoverart_series_mayans_540x796_(1).jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Yellowstone', 'https://flxt.tmsimg.com/assets/p16780458_b_v13_aa.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('1883', 'https://flxt.tmsimg.com/assets/p20531640_b_v13_ab.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Mr. Robot', 'https://flxt.tmsimg.com/assets/p12922738_b1t_v9_aa.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Upload', 'https://m.media-amazon.com/images/M/MV5BYjc5OWU5NzktNTU5MS00NzhiLWE5ZGEtOTIyMjJkOGEwMzQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Better Call Saul', 'https://flxt.tmsimg.com/assets/p15677306_b1t_v9_aa.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Cobra Kai', 'https://resizing.flixster.com/ZZgmKKErY7vE9CNpcs-ewae8dwM=/ems.ZW1zLXByZC1hc3NldHMvdHZzZXJpZXMvUlRUVjc1NjkwMS53ZWJw', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Marvelous Mrs. Maisel', 'https://resizing.flixster.com/dj6QMujogZGSkww-1Dv8DSt7Pz8=/ems.ZW1zLXByZC1hc3NldHMvdHZzZWFzb24vUlRUVjI2NjgxMi53ZWJw', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Peaky Blinders', 'https://m.media-amazon.com/images/M/MV5BMTkzNjEzMDEzMF5BMl5BanBnXkFtZTgwMDI0MjE4MjE@._V1_FMjpg_UX1000_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Mandalorian', 'https://m.media-amazon.com/images/M/MV5BZDhlMzY0ZGItZTcyNS00ZTAxLWIyMmYtZGQ2ODg5OWZiYmJkXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Witcher', 'https://m.media-amazon.com/images/M/MV5BN2FiOWU4YzYtMzZiOS00MzcyLTlkOGEtOTgwZmEwMzAxMzA3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Umbrella Academy', 'https://m.media-amazon.com/images/M/MV5BNzA5MjkwYzMtNGY2MS00YWRjLThkNTktOTNmMzdlZjE3Y2IxXkEyXkFqcGdeQXVyMjkwMzMxODg@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Wanda Vision', 'https://m.media-amazon.com/images/M/MV5BZGEwYmMwZmMtMTQ3MS00YWNhLWEwMmQtZTU5YTIwZmJjZGQ0XkEyXkFqcGdeQXVyMTI5MzA5MjA1._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Wheel of Time', 'https://m.media-amazon.com/images/M/MV5BYzA2Nzk5M2EtNWY4Yi00ZDY4LThkZTgtYjhhNWEyMGY0MjFjXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Glow', 'https://m.media-amazon.com/images/M/MV5BY2RjYzFkZDUtYzNjNC00MzEyLWFmZmItODc2YWFlOWExOWI4XkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Manhunt', 'https://m.media-amazon.com/images/M/MV5BOTcxMjEyMzc4NV5BMl5BanBnXkFtZTgwOTQ4MjE4MjI@._V1_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Space Force', 'https://cdn.mos.cms.futurecdn.net/78p9cUoNYA5U8FqGztGZHM.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Lucifer', 'https://m.media-amazon.com/images/M/MV5BNDJjMzc4NGYtZmFmNS00YWY3LThjMzQtYzJlNGFkZGRiOWI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Silicon Valley', 'https://m.media-amazon.com/images/M/MV5BM2Q5YjNjZWMtYThmYy00N2ZjLWE2NDctNmZjMmZjYWE2NjEwXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Watchmen', 'https://m.media-amazon.com/images/M/MV5BYjhhZDE3NjgtMjkzNC00NzI3LWJhOTItMWQ5ZjljODA5NWNkXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Good Place', 'https://m.media-amazon.com/images/M/MV5BYmMxNjM0NmItNGU1Mi00OGMwLTkzMzctZmE3YjU1ZDE4NmFjXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Person of Interest', 'https://m.media-amazon.com/images/M/MV5BZDU1NzA5YzUtNTdmNy00NTVjLWFhNzEtYWI1NmNkNTA1ZDBhXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Scrubs', 'https://flxt.tmsimg.com/assets/p7892342_b1t_v9_aa.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Ted Lasso', 'https://m.media-amazon.com/images/M/MV5BMDVmODUzNmEtMGMxZC00NWUzLTkxMTAtMDM5OTQzMWE0ZDM3XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Nurse Jackie', 'https://flxt.tmsimg.com/assets/p7894268_b1t_v8_aa.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Justified', 'https://m.media-amazon.com/images/M/MV5BMTgzNjQ4NjM1NF5BMl5BanBnXkFtZTcwNzQ4OTEzNw@@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Deadwood', 'https://m.media-amazon.com/images/M/MV5BNDJhMjUzMDYtNzc4MS00Nzk2LTkyMGQtN2M5NTczYTZmYmY5XkEyXkFqcGdeQXVyMzU3MTc5OTE@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Longmire', 'https://m.media-amazon.com/images/M/MV5BMTcxMzIwNzI3M15BMl5BanBnXkFtZTgwODgxMTU5OTE@._V1_.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Succession', 'https://flxt.tmsimg.com/assets/p15455205_b1t_v9_aa.jpg', 0, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('Hatfield and McCoys', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5716/5716423_so.jpg', 1, 1);
insert into Show (Title, CoverImage, Cancelled, Approved) values ('The Expanse', 'https://m.media-amazon.com/images/M/MV5BZDVmMDljM2QtZDkzZC00ZDg2LWFiMGItZjNiNjliZjg2MGEzXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_FMjpg_UX1000_.jpg', 1, 1);

insert into UserProfile (FirebaseUserId, UserName, Name, Email, Admin) values ('cGTcEAqYt0TB58tdDVOW5ZFuxT23', 'johnx', 'John Smith', 'x@x.com', 0);
insert into UserProfile (FirebaseUserId, UserName, Name, Email, Admin) values ('EbGua89LS5Yk5QaWYgbXKADYWz52', 'jbyrd4', 'Jury Byrd', 'jbyrd4@gmail.com', 0);
insert into UserProfile (FirebaseUserId, UserName, Name, Email, Admin) values ('McZM4oO91NNnHcUbr7g826V4dF43', 'obediahx', 'Obediah Smith', 'obediahx@gmail.com', 1);

insert into Category (Name) values ('Currently Watching');
insert into Category (Name) values ('Finished');
insert into Category (Name) values ('Caught Up');
insert into Category (Name) values ('Lost Interest');
insert into Category (Name) values ('Potential');

insert into Platform (Name) values ('Netflix');
insert into Platform (Name) values ('Amazon Prime');
insert into Platform (Name) values ('Hulu');
insert into Platform (Name) values ('Peacock');
insert into Platform (Name) values ('HBO Max');
insert into Platform (Name) values ('YouTubeTV');
insert into Platform (Name) values ('AppleTV');
insert into Platform (Name) values ('Disney Plus');
insert into Platform (Name) values ('Cruncyroll');
insert into Platform (Name) values ('SlingTV');
insert into Platform (Name) values ('AcornTV');
insert into Platform (Name) values ('CBS All Access');
insert into Platform (Name) values ('Tubi');
insert into Platform (Name) values ('Fubo');